-- The current schema, in one file. The SQLite side keeps its nine migrations because existing
-- databases have to be moved forward step by step; a new PostgreSQL database does not, and
-- 0009's table rebuild with foreign keys disabled has no PostgreSQL equivalent anyway.
--
-- Types are deliberately the same shapes the SQLite side uses: timestamps are TEXT holding
-- ISO-8601, money is integer cents, booleans are 0/1. Converting them to timestamptz and
-- numeric would touch every comparison, every serialisation and every test in the app, and
-- belongs in its own slice once the port is proven.
--
-- Nothing is seeded here. SQLite's 0001 and 0008 seed the `currency` setting and the
-- `sync_epoch` with `INSERT ... randomblob()`; the app writes both on first start instead, so
-- one code path produces them on either backend.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    is_admin      SMALLINT NOT NULL DEFAULT 0,
    lang          TEXT NOT NULL DEFAULT 'en',
    created_at    TEXT NOT NULL
);
-- SQLite spells this `UNIQUE COLLATE NOCASE` on the column. PostgreSQL has no per-column
-- collation of that kind without citext, so the case-insensitive uniqueness is an index --
-- and every lookup of a username must compare `lower(username)` to match it.
CREATE UNIQUE INDEX idx_users_username_lower ON users (lower(username));

CREATE TABLE sessions (
    token      TEXT PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TEXT NOT NULL
);
CREATE INDEX idx_sessions_user ON sessions(user_id);
CREATE INDEX idx_sessions_expires ON sessions(expires_at);

CREATE TABLE settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE objects (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name                 TEXT NOT NULL,
    type                 TEXT NOT NULL CHECK (type IN
                           ('car','e_bike','bike','motorcycle','home','appliance','tool','body','other')),
    counter_unit         TEXT CHECK (counter_unit IN ('km', 'mi', 'h')),
    description          TEXT NOT NULL DEFAULT '',
    purchase_date        TEXT,
    purchase_price_cents BIGINT,
    archived_at          TEXT,
    cover_attachment_id  BIGINT,
    created_at           TEXT NOT NULL,
    updated_at           TEXT NOT NULL,
    fuel_unit            TEXT CHECK (fuel_unit IN ('l', 'gal', 'kwh')),
    client_uuid          TEXT,
    deleted_at           TEXT
);
CREATE INDEX idx_objects_user ON objects(user_id);
CREATE UNIQUE INDEX idx_objects_uuid ON objects(client_uuid);

CREATE TABLE activities (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id      BIGINT NOT NULL REFERENCES objects(id) ON DELETE CASCADE,
    date           TEXT NOT NULL,
    category       TEXT NOT NULL CHECK (category IN
                     ('maintenance','repair','purchase','inspection','modification','fuel','other',
                      'symptom','treatment','appointment','medication')),
    title          TEXT NOT NULL,
    notes          TEXT NOT NULL DEFAULT '',
    counter_value  BIGINT,
    cost_cents     BIGINT,
    created_at     TEXT NOT NULL,
    updated_at     TEXT NOT NULL,
    quantity_milli BIGINT,
    client_op_id   TEXT,
    client_uuid    TEXT,
    deleted_at     TEXT
);
CREATE INDEX idx_activities_object_date ON activities(object_id, date);
CREATE UNIQUE INDEX idx_activities_client_op ON activities(client_op_id) WHERE client_op_id IS NOT NULL;
CREATE UNIQUE INDEX idx_activities_uuid ON activities(client_uuid);

CREATE TABLE files (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    sha256        TEXT NOT NULL,
    original_name TEXT NOT NULL,
    mime          TEXT NOT NULL,
    size          BIGINT NOT NULL,
    width         BIGINT,
    height        BIGINT,
    taken_at      TEXT,
    created_at    TEXT NOT NULL,
    client_uuid   TEXT,
    deleted_at    TEXT,
    UNIQUE (user_id, sha256)
);
CREATE UNIQUE INDEX idx_files_uuid ON files(client_uuid);

CREATE TABLE attachments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id    BIGINT NOT NULL REFERENCES objects(id) ON DELETE CASCADE,
    activity_id  BIGINT REFERENCES activities(id) ON DELETE CASCADE,
    file_id      BIGINT NOT NULL REFERENCES files(id) ON DELETE RESTRICT,
    kind         TEXT NOT NULL CHECK (kind IN ('photo', 'document')),
    caption      TEXT NOT NULL DEFAULT '',
    created_at   TEXT NOT NULL,
    client_op_id TEXT,
    client_uuid  TEXT,
    deleted_at   TEXT
);
CREATE INDEX idx_attachments_object ON attachments(object_id);
CREATE INDEX idx_attachments_activity ON attachments(activity_id);
CREATE INDEX idx_attachments_file ON attachments(file_id);
CREATE UNIQUE INDEX idx_attachments_client_op ON attachments(client_op_id) WHERE client_op_id IS NOT NULL;
CREATE UNIQUE INDEX idx_attachments_uuid ON attachments(client_uuid);

CREATE TABLE reminders (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id        BIGINT NOT NULL REFERENCES objects(id) ON DELETE CASCADE,
    title            TEXT NOT NULL,
    notes            TEXT NOT NULL DEFAULT '',
    due_date         TEXT,
    due_counter      BIGINT,
    repeat_months    BIGINT,
    repeat_counter   BIGINT,
    done_at          TEXT,
    done_activity_id BIGINT REFERENCES activities(id) ON DELETE SET NULL,
    created_at       TEXT NOT NULL,
    snoozed_until    TEXT,
    client_uuid      TEXT,
    deleted_at       TEXT,
    CHECK (due_date IS NOT NULL OR due_counter IS NOT NULL)
);
CREATE INDEX idx_reminders_object ON reminders(object_id);
CREATE UNIQUE INDEX idx_reminders_uuid ON reminders(client_uuid);

CREATE TABLE api_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name         TEXT NOT NULL,
    token_hash   TEXT NOT NULL UNIQUE,
    prefix       TEXT NOT NULL,
    created_at   TEXT NOT NULL,
    last_used_at TEXT
);
CREATE INDEX idx_api_tokens_user ON api_tokens(user_id);

-- `seq` is the pull cursor. On SQLite it is monotonic, gapless and in commit order because
-- SQLite has one writer. PostgreSQL does not give that for free, and an identity column here
-- would be wrong twice over: it hands out numbers that survive a rollback, and concurrent
-- transactions can commit out of order, so a device can read past a number that has not
-- committed and never see it again. Part two of this project assigns `seq` under an advisory
-- lock. Until then this column is plain BIGINT and nothing may write to it concurrently.
CREATE TABLE changes (
    seq          BIGINT PRIMARY KEY,
    entity       TEXT NOT NULL CHECK (entity IN ('object','activity','reminder','attachment','file')),
    entity_uuid  TEXT NOT NULL,
    op           TEXT NOT NULL CHECK (op IN ('create','set','delete')),
    field        TEXT,
    value        TEXT,
    edited_at    TEXT NOT NULL,
    applied_at   TEXT NOT NULL,
    user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id    TEXT NOT NULL,
    client_op_id TEXT NOT NULL
);
CREATE INDEX idx_changes_user_seq ON changes(user_id, seq);
CREATE UNIQUE INDEX idx_changes_user_op ON changes(user_id, client_op_id);

CREATE TABLE field_clock (
    entity      TEXT NOT NULL,
    entity_uuid TEXT NOT NULL,
    field       TEXT NOT NULL,
    edited_at   TEXT NOT NULL,
    device_id   TEXT NOT NULL,
    PRIMARY KEY (entity, entity_uuid, field)
);
