-- Notifications per person; SQLite's 0012 makes the same change.
ALTER TABLE users ADD COLUMN notify_url TEXT;
ALTER TABLE users ADD COLUMN notify_format TEXT NOT NULL DEFAULT 'text' CHECK (notify_format IN ('json', 'text'));

CREATE TABLE push_subscriptions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    endpoint   TEXT NOT NULL,
    p256dh     TEXT NOT NULL,
    auth       TEXT NOT NULL,
    created_at TEXT NOT NULL
);
CREATE UNIQUE INDEX idx_push_subscriptions_endpoint ON push_subscriptions(endpoint);
CREATE INDEX idx_push_subscriptions_user ON push_subscriptions(user_id);
