-- Each user's own object types. An object refers to one as `custom:<client_uuid>` -- the uuid,
-- not the id, so a type and the objects using it can be created offline in one go.
CREATE TABLE object_types (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    client_uuid  TEXT NOT NULL UNIQUE,
    name         TEXT NOT NULL,
    icon         TEXT NOT NULL,
    categories   TEXT NOT NULL,
    counter_unit TEXT CHECK (counter_unit IN ('km','mi','h')),
    created_at   TEXT NOT NULL,
    updated_at   TEXT NOT NULL,
    deleted_at   TEXT
);
CREATE INDEX idx_object_types_user ON object_types(user_id);

-- A custom key cannot be listed in a CHECK, so validity moves to
-- `object_type::is_valid_for_user`; the column stays NOT NULL. The name is PostgreSQL's default
-- for the unnamed CHECK in 0001, confirmed against a migrated database.
ALTER TABLE objects DROP CONSTRAINT objects_type_check;
