CREATE TABLE telegram_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    token_cipher TEXT NOT NULL,
    token_nonce TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    bot_username TEXT NOT NULL,
    update_offset TEXT NOT NULL DEFAULT '0',
    last_error TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
